- name: Configure postgres postgresql.conf
  template:
    src: postgresql96.conf.j2 
    dest: /etc/postgresql/9.6/main/postgresql.conf
    owner: root
    group: root
    mode:  0644
  notify:
    - restart postgresql

- name: Configure postgres pg_hba.conf
  template:
    src: postgresql96.pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    owner: root
    group: root
    mode:  0644
  notify:
    - restart postgresql

- name: Check postgresql started
  service:
    name: postgresql
    state: started

