- name: PG Create User {{ database_user }}
  become_user: postgres
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ database_pass }}"
    port: 5432
    role_attr_flags: REPLICATION  
  when: database_pass is defined and database_user is defined

