---

- name: Install xenial-pgdg
  apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    filename: 'pgdg'
    state: present
    update_cache: 'yes'

- name: Install postgresql-9.6
  apt:
    name:
      - postgresql-9.6
      - python-psycopg2
    state: present
    update_cache: yes

- name: Check postgresql started
  service:
    name: postgresql
    state: stopped

- name: Clear Postgresql Data folder
  file:
    state: absent
    path: "/var/lib/postgresql/9.6/main/"

- name: Restore Postgresql Data folder from master
  remote_user: postgres
  shell: export PGPASSWORD="{{ database_pass }}" && /usr/lib/postgresql/9.6/bin/pg_basebackup -h {{ master_ip }} -U {{ database_user }} -D /var/lib/postgresql/9.6/main -P -v --xlog-method=stream 2>&1

- name: Configure Postgres configs
  include: configure_postgres_server.yml
